sonar.projectKey=DevSecOps-project-end-to-end
sonar.projectName=DevSecOps-project-end-to-end
sonar.projectVersion=1.0

sonar.source=.
sonar.exlusions=node_modules/**

sonar.projectKey=myproject
sonar.sources=.
sonar.host.url=http://13.221.138.38:9000
