name: 
on: 
    push:
        branches:
            - qa
        paths: 
            - client/**
            - server/**
            - .github/workflows/cd.yaml
jobs:
    gileak-scan:
        name: Gitleak scan
        runs-on: ubuntu-latest 
        steps: 
            - name: code checkout 
              uses: actions/checkout@v6

            - name: gitleak scan
              run: | 
                docker run --rm -v "${{ github.workspace }}:/repo" \
                zricethezav/gitleaks:latest  detect \
                --source=/repo \
                --report-format=json \
                --report-path=/repo/gitleaks-report.json \
                --redact --exit-code 0


            - name: collect artifact
              uses: actions/upload-artifact@v7
              with:
                name: artifact
                path: gitleaks-report.json
                if-no-files-found: warn

    client-trivy-fs:
       name: Client trivy FS scan
       runs-on: ubuntu-latest
       needs: gileak-scan
       steps:
        - name: code checkout 
          uses: actions/checkout@v6
          
        - name: install Trivy
          uses: aquasecurity/setup-trivy@v0.2.6
          with: 
            version: latest
            cache: true
         
        - name: checing the version
          run: |
           trivy --version
           which trivy
           
        - name: run trivy FS scan on client (JSON)
          run : |
           trivy fs ./client \
           --format json \
           --output client-trivy-fs-report.json \
           --severity HIGH,CRITICAL \
           --ignore-unfixed \
           --exit-code 0               
          #exit is to run the pipline even if it find error
 
        - name: run trivy FS scan on client (TABLE)
          run : |
           trivy fs ./client \
           --format table \
           --severity HIGH,CRITICAL \
           --ignore-unfixed \
           --exit-code 0 > client-trivy-fs-report.txt

  # UPLOAD FILE FOR CLIENT    

        - name: Upload CLIENT JSON
          uses: actions/upload-artifact@v7
          with:
            name: client-trivy-fs-report
            path: client-report.json
            if-no-files-found: warn

        - name: Upload CLIENT TABLE
          uses: actions/upload-artifact@v7
          with:
            name: client-trivy-fs-report
            path: client-report.txt
            if-no-files-found: warn

 
    Server-trivy-fs: 
      name: server trivy
      runs-on: ubuntu-latest
      needs: gileak-scan
      steps:
        - name: code checkout
          uses: actions/checkout@v6

        - name: install trivy
          uses: aquasecurity/setup-trivy@v0.2.6
          with:
            version: latest
            cache: true

        - name: run scan (JSON)
          run: |

           trivy fs ./server \
           --format json \
           --output server-trivy-report.json \
           --severity HIGH,CRITICAL \
           --ignore-unfixed \
           --exit-code 0 

        - name: runnning scan for (TABLE)
          run: |
           trivy fs ./server \
           --format table \
           --severity HIGH,CRITICAL \
           --ignore-unfixed \
           --exit-code 0 > server-table-report.txt

#UPLOAD FILE FOR SERVER:
        - name: uplpoad SEVER file
          uses: actions/upload-artifact@v7
          with:
            name: server-trivy-report
            path: server-trivy-report.json
            if-no-files-found: warn

        - name: upload server TABLE
          uses: actions/upload-artifact@v7
          with:
            name: server-table-report
            path: server-table-report.txt
            if-no-files-found: warn 