name: 
on: 
    push:
        branches:
            - qa
        paths: 
            - client/**
            - server/**
            - .github/workflows/cd.yaml
jobs:
    gileak-scan:
        name: Gitleak scan
        runs-on: ubuntu-latest 
        steps: 
            - name: code checkout 
              uses: actions/checkout@v4

            - name: gitleak scan
              run: | 
                docker run --rm -v "${{ github.workspace }}:/repo" \
                zricethezav/gitleaks:latest  detect \
                --source=/repo \
                --report-format=json \
                --report-path=/repo/gitleaks-report.json \
                --redact --exit-code 0


            - name: collect artifact
              uses: actions/upload-artifact@v4
              with:
                name: artifact
                path: gitleaks-report.json
                if-no-files-found: warn


 


    